### ISSUE TITLE
Can't open in Xcode 12.4

### ISSUE THREAD

**Issue by sz-zdy** [ewersoncastelo/Custom-Button-with-badge#1]
Hi, I clone your repo and want to open it in Xcode 12.4. But it failed. The prompt is as follows
![image](https://user-images.githubusercontent.com/30308838/140243494-9254acda-c78d-4c4d-a002-60702c73462c.png)

**Comment by ewersoncastelo** [comment]
Hi, you must be have Xcode Version 13.1 or high
